Rails.application.routes.draw do
  get 'people/find'
  post 'people/find', to: 'people#find'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people/index'
  get 'people/edit/:id', to: 'people#edit'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/delete/:id', to: 'people#delete'
  get 'people/:id', to: 'people#show'
  get 'msgboard/index'
  post 'msgboard/index'
  get 'hello' => 'start#hello'
  get 'index' => 'start#index'
  post 'index' => 'start#index'
end
